//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAMS_WCF.Contracts
{
  using System.Runtime.Serialization;


  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
  [System.Runtime.Serialization.DataContractAttribute(Name = "PkgLastPositionResults", Namespace = "http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
  public partial class PkgLastPositionResults : object, System.Runtime.Serialization.IExtensibleDataObject
  {

    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

    private CAMS_WCF.Contracts.LastPositionParams[] PositionsField;

    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
      get
      {
        return this.extensionDataField;
      }
      set
      {
        this.extensionDataField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public CAMS_WCF.Contracts.LastPositionParams[] Positions
    {
      get
      {
        return this.PositionsField;
      }
      set
      {
        this.PositionsField = value;
      }
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
  [System.Runtime.Serialization.DataContractAttribute(Name = "LastPositionParams", Namespace = "http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
  public partial class LastPositionParams : object, System.Runtime.Serialization.IExtensibleDataObject
  {

    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

    private CAMS_WCF.Contracts.AssetId AssetidField;

    private string ClientNameField;

    private double HeadingField;

    private System.DateTime LastHeardGMTField;

    private System.DateTime LastPosHeardGMTField;

    private double LatField;

    private double LngField;

    private double SpeedField;

    private uint StateField;

    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
      get
      {
        return this.extensionDataField;
      }
      set
      {
        this.extensionDataField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public CAMS_WCF.Contracts.AssetId Assetid
    {
      get
      {
        return this.AssetidField;
      }
      set
      {
        this.AssetidField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string ClientName
    {
      get
      {
        return this.ClientNameField;
      }
      set
      {
        this.ClientNameField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public double Heading
    {
      get
      {
        return this.HeadingField;
      }
      set
      {
        this.HeadingField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime LastHeardGMT
    {
      get
      {
        return this.LastHeardGMTField;
      }
      set
      {
        this.LastHeardGMTField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime LastPosHeardGMT
    {
      get
      {
        return this.LastPosHeardGMTField;
      }
      set
      {
        this.LastPosHeardGMTField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public double Lat
    {
      get
      {
        return this.LatField;
      }
      set
      {
        this.LatField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public double Lng
    {
      get
      {
        return this.LngField;
      }
      set
      {
        this.LngField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public double Speed
    {
      get
      {
        return this.SpeedField;
      }
      set
      {
        this.SpeedField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public uint State
    {
      get
      {
        return this.StateField;
      }
      set
      {
        this.StateField = value;
      }
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
  [System.Runtime.Serialization.DataContractAttribute(Name = "AssetId", Namespace = "http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
  public partial class AssetId : object, System.Runtime.Serialization.IExtensibleDataObject
  {

    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

    private ushort IdField;

    private string ServerNameField;

    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
      get
      {
        return this.extensionDataField;
      }
      set
      {
        this.extensionDataField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public ushort Id
    {
      get
      {
        return this.IdField;
      }
      set
      {
        this.IdField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string ServerName
    {
      get
      {
        return this.ServerNameField;
      }
      set
      {
        this.ServerNameField = value;
      }
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
  [System.Runtime.Serialization.DataContractAttribute(Name = "MaintenanceRequest", Namespace = "http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
  public partial class MaintenanceRequest : object, System.Runtime.Serialization.IExtensibleDataObject
  {

    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

    private CAMS_WCF.Contracts.AssetId AssetidField;

    private System.DateTime EndGMTField;

    private System.DateTime StartGMTField;

    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
      get
      {
        return this.extensionDataField;
      }
      set
      {
        this.extensionDataField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public CAMS_WCF.Contracts.AssetId Assetid
    {
      get
      {
        return this.AssetidField;
      }
      set
      {
        this.AssetidField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime EndGMT
    {
      get
      {
        return this.EndGMTField;
      }
      set
      {
        this.EndGMTField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime StartGMT
    {
      get
      {
        return this.StartGMTField;
      }
      set
      {
        this.StartGMTField = value;
      }
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
  [System.Runtime.Serialization.DataContractAttribute(Name = "PkgMaintenanceResults", Namespace = "http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
  public partial class PkgMaintenanceResults : object, System.Runtime.Serialization.IExtensibleDataObject
  {

    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

    private CAMS_WCF.Contracts.MaintenanceParams[] pkgField;

    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
      get
      {
        return this.extensionDataField;
      }
      set
      {
        this.extensionDataField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public CAMS_WCF.Contracts.MaintenanceParams[] pkg
    {
      get
      {
        return this.pkgField;
      }
      set
      {
        this.pkgField = value;
      }
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
  [System.Runtime.Serialization.DataContractAttribute(Name = "MaintenanceParams", Namespace = "http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
  public partial class MaintenanceParams : object, System.Runtime.Serialization.IExtensibleDataObject
  {

    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

    private CAMS_WCF.Contracts.AssetId AssetidField;

    private ushort ClientIdField;

    private string ClientNameField;

    private System.DateTime EndGMTField;

    private System.DateTime StartGMTField;

    private double TotalHoursField;

    private double TotalMetersField;

    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
      get
      {
        return this.extensionDataField;
      }
      set
      {
        this.extensionDataField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public CAMS_WCF.Contracts.AssetId Assetid
    {
      get
      {
        return this.AssetidField;
      }
      set
      {
        this.AssetidField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public ushort ClientId
    {
      get
      {
        return this.ClientIdField;
      }
      set
      {
        this.ClientIdField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string ClientName
    {
      get
      {
        return this.ClientNameField;
      }
      set
      {
        this.ClientNameField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime EndGMT
    {
      get
      {
        return this.EndGMTField;
      }
      set
      {
        this.EndGMTField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime StartGMT
    {
      get
      {
        return this.StartGMTField;
      }
      set
      {
        this.StartGMTField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public double TotalHours
    {
      get
      {
        return this.TotalHoursField;
      }
      set
      {
        this.TotalHoursField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public double TotalMeters
    {
      get
      {
        return this.TotalMetersField;
      }
      set
      {
        this.TotalMetersField = value;
      }
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
  [System.Runtime.Serialization.DataContractAttribute(Name = "PkgAssetFilterResults", Namespace = "http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
  public partial class PkgAssetFilterResults : object, System.Runtime.Serialization.IExtensibleDataObject
  {

    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

    private CAMS_WCF.Contracts.AssetFilterParams[] AssetsField;

    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
      get
      {
        return this.extensionDataField;
      }
      set
      {
        this.extensionDataField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public CAMS_WCF.Contracts.AssetFilterParams[] Assets
    {
      get
      {
        return this.AssetsField;
      }
      set
      {
        this.AssetsField = value;
      }
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
  [System.Runtime.Serialization.DataContractAttribute(Name = "AssetFilterParams", Namespace = "http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
  public partial class AssetFilterParams : object, System.Runtime.Serialization.IExtensibleDataObject
  {

    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

    private CAMS_WCF.Contracts.AssetInfo AInfoField;

    private CAMS_WCF.Contracts.AssetFilterParams.ActiveStates ActiveStateField;

    private CAMS_WCF.Contracts.AssetFilterParams.Densities DensityField;

    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
      get
      {
        return this.extensionDataField;
      }
      set
      {
        this.extensionDataField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public CAMS_WCF.Contracts.AssetInfo AInfo
    {
      get
      {
        return this.AInfoField;
      }
      set
      {
        this.AInfoField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public CAMS_WCF.Contracts.AssetFilterParams.ActiveStates ActiveState
    {
      get
      {
        return this.ActiveStateField;
      }
      set
      {
        this.ActiveStateField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public CAMS_WCF.Contracts.AssetFilterParams.Densities Density
    {
      get
      {
        return this.DensityField;
      }
      set
      {
        this.DensityField = value;
      }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AssetFilterParams.ActiveStates", Namespace = "http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
    public enum ActiveStates : int
    {

      [System.Runtime.Serialization.EnumMemberAttribute()]
      Deactive = 0,

      [System.Runtime.Serialization.EnumMemberAttribute()]
      Active = 1,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AssetFilterParams.Densities", Namespace = "http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
    public enum Densities : int
    {

      [System.Runtime.Serialization.EnumMemberAttribute()]
      Sparse = 1,

      [System.Runtime.Serialization.EnumMemberAttribute()]
      Dense = 2,
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
  [System.Runtime.Serialization.DataContractAttribute(Name = "AssetInfo", Namespace = "http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
  public partial class AssetInfo : object, System.Runtime.Serialization.IExtensibleDataObject
  {

    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

    private string AssetNameField;

    private string AssetTypeField;

    private CAMS_WCF.Contracts.AssetId AssetidField;

    private string ClientNameField;

    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
      get
      {
        return this.extensionDataField;
      }
      set
      {
        this.extensionDataField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string AssetName
    {
      get
      {
        return this.AssetNameField;
      }
      set
      {
        this.AssetNameField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string AssetType
    {
      get
      {
        return this.AssetTypeField;
      }
      set
      {
        this.AssetTypeField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public CAMS_WCF.Contracts.AssetId Assetid
    {
      get
      {
        return this.AssetidField;
      }
      set
      {
        this.AssetidField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string ClientName
    {
      get
      {
        return this.ClientNameField;
      }
      set
      {
        this.ClientNameField = value;
      }
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
  [System.Runtime.Serialization.DataContractAttribute(Name = "PkgEventFilterResults", Namespace = "http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
  public partial class PkgEventFilterResults : object, System.Runtime.Serialization.IExtensibleDataObject
  {

    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

    private System.Collections.Generic.Dictionary<string, CAMS_WCF.Contracts.EventFilterParams[]> EventTypesField;

    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
      get
      {
        return this.extensionDataField;
      }
      set
      {
        this.extensionDataField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.Collections.Generic.Dictionary<string, CAMS_WCF.Contracts.EventFilterParams[]> EventTypes
    {
      get
      {
        return this.EventTypesField;
      }
      set
      {
        this.EventTypesField = value;
      }
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
  [System.Runtime.Serialization.DataContractAttribute(Name = "EventFilterParams", Namespace = "http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
  public partial class EventFilterParams : CAMS_WCF.Contracts.EventFilterBase
  {

    private string AssetTypeField;

    private string ClientNameField;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string AssetType
    {
      get
      {
        return this.AssetTypeField;
      }
      set
      {
        this.AssetTypeField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string ClientName
    {
      get
      {
        return this.ClientNameField;
      }
      set
      {
        this.ClientNameField = value;
      }
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
  [System.Runtime.Serialization.DataContractAttribute(Name = "PkgEventFilterBaseResults", Namespace = "http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
  public partial class PkgEventFilterBaseResults : object, System.Runtime.Serialization.IExtensibleDataObject
  {

    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

    private System.Collections.Generic.Dictionary<string, CAMS_WCF.Contracts.EventFilterBase[]> EventTypesField;

    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
      get
      {
        return this.extensionDataField;
      }
      set
      {
        this.extensionDataField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.Collections.Generic.Dictionary<string, CAMS_WCF.Contracts.EventFilterBase[]> EventTypes
    {
      get
      {
        return this.EventTypesField;
      }
      set
      {
        this.EventTypesField = value;
      }
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
  [System.Runtime.Serialization.DataContractAttribute(Name = "EventFilterBase", Namespace = "http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
  [System.Runtime.Serialization.KnownTypeAttribute(typeof(CAMS_WCF.Contracts.EventFilterParams))]
  public partial class EventFilterBase : object, System.Runtime.Serialization.IExtensibleDataObject
  {

    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

    private CAMS_WCF.Contracts.EventFilterBase.EventDataTypes EventDataTypeField;

    private string EventTypeField;

    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
      get
      {
        return this.extensionDataField;
      }
      set
      {
        this.extensionDataField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public CAMS_WCF.Contracts.EventFilterBase.EventDataTypes EventDataType
    {
      get
      {
        return this.EventDataTypeField;
      }
      set
      {
        this.EventDataTypeField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string EventType
    {
      get
      {
        return this.EventTypeField;
      }
      set
      {
        this.EventTypeField = value;
      }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EventFilterBase.EventDataTypes", Namespace = "http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
    public enum EventDataTypes : int
    {

      [System.Runtime.Serialization.EnumMemberAttribute()]
      Point = 1,

      [System.Runtime.Serialization.EnumMemberAttribute()]
      Line = 2,
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
  [System.Runtime.Serialization.DataContractAttribute(Name = "PkgAssetStatesParams", Namespace = "http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
  public partial class PkgAssetStatesParams : object, System.Runtime.Serialization.IExtensibleDataObject
  {

    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

    private System.Collections.Generic.Dictionary<CAMS_WCF.Contracts.AssetId, CAMS_WCF.Contracts.AssetStateParams[]> AssetStatesField;

    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
      get
      {
        return this.extensionDataField;
      }
      set
      {
        this.extensionDataField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.Collections.Generic.Dictionary<CAMS_WCF.Contracts.AssetId, CAMS_WCF.Contracts.AssetStateParams[]> AssetStates
    {
      get
      {
        return this.AssetStatesField;
      }
      set
      {
        this.AssetStatesField = value;
      }
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
  [System.Runtime.Serialization.DataContractAttribute(Name = "AssetStateParams", Namespace = "http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
  public partial class AssetStateParams : object, System.Runtime.Serialization.IExtensibleDataObject
  {

    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

    private ulong StateField;

    private string StateDscrField;

    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
      get
      {
        return this.extensionDataField;
      }
      set
      {
        this.extensionDataField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public ulong State
    {
      get
      {
        return this.StateField;
      }
      set
      {
        this.StateField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string StateDscr
    {
      get
      {
        return this.StateDscrField;
      }
      set
      {
        this.StateDscrField = value;
      }
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
  [System.Runtime.Serialization.DataContractAttribute(Name = "PkgQueryResultParams", Namespace = "http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
  public partial class PkgQueryResultParams : object, System.Runtime.Serialization.IExtensibleDataObject
  {

    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

    private CAMS_WCF.Contracts.QueryResultParams[] QueryResultsField;

    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
      get
      {
        return this.extensionDataField;
      }
      set
      {
        this.extensionDataField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public CAMS_WCF.Contracts.QueryResultParams[] QueryResults
    {
      get
      {
        return this.QueryResultsField;
      }
      set
      {
        this.QueryResultsField = value;
      }
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
  [System.Runtime.Serialization.DataContractAttribute(Name = "QueryResultParams", Namespace = "http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
  public partial class QueryResultParams : object, System.Runtime.Serialization.IExtensibleDataObject
  {

    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

    private CAMS_WCF.Contracts.AssetInfo AInfoField;

    private CAMS_WCF.Contracts.QueryResultParams.Densities DensityField;

    private uint DistanceField;

    private System.DateTime EndTimeGMTField;

    private uint EventIdField;

    private string EventTypeField;

    private System.DateTime StartTimeGMTField;

    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
      get
      {
        return this.extensionDataField;
      }
      set
      {
        this.extensionDataField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public CAMS_WCF.Contracts.AssetInfo AInfo
    {
      get
      {
        return this.AInfoField;
      }
      set
      {
        this.AInfoField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public CAMS_WCF.Contracts.QueryResultParams.Densities Density
    {
      get
      {
        return this.DensityField;
      }
      set
      {
        this.DensityField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public uint Distance
    {
      get
      {
        return this.DistanceField;
      }
      set
      {
        this.DistanceField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime EndTimeGMT
    {
      get
      {
        return this.EndTimeGMTField;
      }
      set
      {
        this.EndTimeGMTField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public uint EventId
    {
      get
      {
        return this.EventIdField;
      }
      set
      {
        this.EventIdField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string EventType
    {
      get
      {
        return this.EventTypeField;
      }
      set
      {
        this.EventTypeField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime StartTimeGMT
    {
      get
      {
        return this.StartTimeGMTField;
      }
      set
      {
        this.StartTimeGMTField = value;
      }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "QueryResultParams.Densities", Namespace = "http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
    public enum Densities : int
    {

      [System.Runtime.Serialization.EnumMemberAttribute()]
      Sparse = 1,

      [System.Runtime.Serialization.EnumMemberAttribute()]
      Dense = 2,
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
  [System.Runtime.Serialization.DataContractAttribute(Name = "PkgRealtimePointResults", Namespace = "http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
  public partial class PkgRealtimePointResults : object, System.Runtime.Serialization.IExtensibleDataObject
  {

    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

    private System.Collections.Generic.Dictionary<CAMS_WCF.Contracts.AssetId, CAMS_WCF.Contracts.RealtimePointParams[]> RTPointsField;

    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
      get
      {
        return this.extensionDataField;
      }
      set
      {
        this.extensionDataField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.Collections.Generic.Dictionary<CAMS_WCF.Contracts.AssetId, CAMS_WCF.Contracts.RealtimePointParams[]> RTPoints
    {
      get
      {
        return this.RTPointsField;
      }
      set
      {
        this.RTPointsField = value;
      }
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
  [System.Runtime.Serialization.DataContractAttribute(Name = "RealtimePointParams", Namespace = "http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
  public partial class RealtimePointParams : object, System.Runtime.Serialization.IExtensibleDataObject
  {

    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

    private double LatField;

    private double LngField;

    private int SpeedField;

    private int StateField;

    private System.DateTime TimeGMTField;

    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
      get
      {
        return this.extensionDataField;
      }
      set
      {
        this.extensionDataField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public double Lat
    {
      get
      {
        return this.LatField;
      }
      set
      {
        this.LatField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public double Lng
    {
      get
      {
        return this.LngField;
      }
      set
      {
        this.LngField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public int Speed
    {
      get
      {
        return this.SpeedField;
      }
      set
      {
        this.SpeedField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public int State
    {
      get
      {
        return this.StateField;
      }
      set
      {
        this.StateField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime TimeGMT
    {
      get
      {
        return this.TimeGMTField;
      }
      set
      {
        this.TimeGMTField = value;
      }
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
  [System.Runtime.Serialization.DataContractAttribute(Name = "PlotPointRequest", Namespace = "http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
  public partial class PlotPointRequest : object, System.Runtime.Serialization.IExtensibleDataObject
  {

    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

    private CAMS_WCF.Contracts.EventAssetId EAIdField;

    private System.DateTime EndGMTField;

    private System.DateTime StartGMTField;

    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
      get
      {
        return this.extensionDataField;
      }
      set
      {
        this.extensionDataField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public CAMS_WCF.Contracts.EventAssetId EAId
    {
      get
      {
        return this.EAIdField;
      }
      set
      {
        this.EAIdField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime EndGMT
    {
      get
      {
        return this.EndGMTField;
      }
      set
      {
        this.EndGMTField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime StartGMT
    {
      get
      {
        return this.StartGMTField;
      }
      set
      {
        this.StartGMTField = value;
      }
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
  [System.Runtime.Serialization.DataContractAttribute(Name = "EventAssetId", Namespace = "http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
  public partial class EventAssetId : object, System.Runtime.Serialization.IExtensibleDataObject
  {

    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

    private CAMS_WCF.Contracts.AssetId AssetidField;

    private uint IdField;

    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
      get
      {
        return this.extensionDataField;
      }
      set
      {
        this.extensionDataField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public CAMS_WCF.Contracts.AssetId Assetid
    {
      get
      {
        return this.AssetidField;
      }
      set
      {
        this.AssetidField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public uint Id
    {
      get
      {
        return this.IdField;
      }
      set
      {
        this.IdField = value;
      }
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
  [System.Runtime.Serialization.DataContractAttribute(Name = "PkgPlotPointResults", Namespace = "http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
  public partial class PkgPlotPointResults : object, System.Runtime.Serialization.IExtensibleDataObject
  {

    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

    private System.Collections.Generic.Dictionary<CAMS_WCF.Contracts.EventId, CAMS_WCF.Contracts.RealtimePointParams[]> PlotPointsField;

    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
      get
      {
        return this.extensionDataField;
      }
      set
      {
        this.extensionDataField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.Collections.Generic.Dictionary<CAMS_WCF.Contracts.EventId, CAMS_WCF.Contracts.RealtimePointParams[]> PlotPoints
    {
      get
      {
        return this.PlotPointsField;
      }
      set
      {
        this.PlotPointsField = value;
      }
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
  [System.Runtime.Serialization.DataContractAttribute(Name = "EventId", Namespace = "http://schemas.datacontract.org/2004/07/CAMS_WCF.Contracts")]
  public partial class EventId : object, System.Runtime.Serialization.IExtensibleDataObject
  {

    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

    private uint IdField;

    private string ServerNameField;

    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
      get
      {
        return this.extensionDataField;
      }
      set
      {
        this.extensionDataField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public uint Id
    {
      get
      {
        return this.IdField;
      }
      set
      {
        this.IdField = value;
      }
    }

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string ServerName
    {
      get
      {
        return this.ServerNameField;
      }
      set
      {
        this.ServerNameField = value;
      }
    }
  }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "ICAMSDataInterface")]
public interface ICAMSDataInterface
{

  [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAMSDataInterface/GetLastPositionInfoAll", ReplyAction = "http://tempuri.org/ICAMSDataInterface/GetLastPositionInfoAllResponse")]
  CAMS_WCF.Contracts.PkgLastPositionResults GetLastPositionInfoAll();

  [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAMSDataInterface/GetLastPositionInfoAll", ReplyAction = "http://tempuri.org/ICAMSDataInterface/GetLastPositionInfoAllResponse")]
  System.Threading.Tasks.Task<CAMS_WCF.Contracts.PkgLastPositionResults> GetLastPositionInfoAllAsync();

  [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAMSDataInterface/GetLastPositionInfo", ReplyAction = "http://tempuri.org/ICAMSDataInterface/GetLastPositionInfoResponse")]
  CAMS_WCF.Contracts.PkgLastPositionResults GetLastPositionInfo(CAMS_WCF.Contracts.AssetId[] ads);

  [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAMSDataInterface/GetLastPositionInfo", ReplyAction = "http://tempuri.org/ICAMSDataInterface/GetLastPositionInfoResponse")]
  System.Threading.Tasks.Task<CAMS_WCF.Contracts.PkgLastPositionResults> GetLastPositionInfoAsync(CAMS_WCF.Contracts.AssetId[] ads);

  [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAMSDataInterface/GetMaintenanceInfo", ReplyAction = "http://tempuri.org/ICAMSDataInterface/GetMaintenanceInfoResponse")]
  CAMS_WCF.Contracts.PkgMaintenanceResults GetMaintenanceInfo(CAMS_WCF.Contracts.MaintenanceRequest[] mr);

  [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAMSDataInterface/GetMaintenanceInfo", ReplyAction = "http://tempuri.org/ICAMSDataInterface/GetMaintenanceInfoResponse")]
  System.Threading.Tasks.Task<CAMS_WCF.Contracts.PkgMaintenanceResults> GetMaintenanceInfoAsync(CAMS_WCF.Contracts.MaintenanceRequest[] mr);

  [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAMSDataInterface/GetMaintenanceAssets", ReplyAction = "http://tempuri.org/ICAMSDataInterface/GetMaintenanceAssetsResponse")]
  CAMS_WCF.Contracts.PkgAssetFilterResults GetMaintenanceAssets();

  [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAMSDataInterface/GetMaintenanceAssets", ReplyAction = "http://tempuri.org/ICAMSDataInterface/GetMaintenanceAssetsResponse")]
  System.Threading.Tasks.Task<CAMS_WCF.Contracts.PkgAssetFilterResults> GetMaintenanceAssetsAsync();

  [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAMSDataInterface/GetAssetFilters", ReplyAction = "http://tempuri.org/ICAMSDataInterface/GetAssetFiltersResponse")]
  CAMS_WCF.Contracts.PkgAssetFilterResults GetAssetFilters();

  [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAMSDataInterface/GetAssetFilters", ReplyAction = "http://tempuri.org/ICAMSDataInterface/GetAssetFiltersResponse")]
  System.Threading.Tasks.Task<CAMS_WCF.Contracts.PkgAssetFilterResults> GetAssetFiltersAsync();

  [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAMSDataInterface/GetEventFilters", ReplyAction = "http://tempuri.org/ICAMSDataInterface/GetEventFiltersResponse")]
  CAMS_WCF.Contracts.PkgEventFilterResults GetEventFilters();

  [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAMSDataInterface/GetEventFilters", ReplyAction = "http://tempuri.org/ICAMSDataInterface/GetEventFiltersResponse")]
  System.Threading.Tasks.Task<CAMS_WCF.Contracts.PkgEventFilterResults> GetEventFiltersAsync();

  [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAMSDataInterface/GetEventFiltersFromAsset", ReplyAction = "http://tempuri.org/ICAMSDataInterface/GetEventFiltersFromAssetResponse")]
  CAMS_WCF.Contracts.PkgEventFilterBaseResults GetEventFiltersFromAsset(CAMS_WCF.Contracts.AssetId aid);

  [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAMSDataInterface/GetEventFiltersFromAsset", ReplyAction = "http://tempuri.org/ICAMSDataInterface/GetEventFiltersFromAssetResponse")]
  System.Threading.Tasks.Task<CAMS_WCF.Contracts.PkgEventFilterBaseResults> GetEventFiltersFromAssetAsync(CAMS_WCF.Contracts.AssetId aid);

  [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAMSDataInterface/GetAssetStates", ReplyAction = "http://tempuri.org/ICAMSDataInterface/GetAssetStatesResponse")]
  CAMS_WCF.Contracts.PkgAssetStatesParams GetAssetStates(CAMS_WCF.Contracts.AssetId[] ads);

  [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAMSDataInterface/GetAssetStates", ReplyAction = "http://tempuri.org/ICAMSDataInterface/GetAssetStatesResponse")]
  System.Threading.Tasks.Task<CAMS_WCF.Contracts.PkgAssetStatesParams> GetAssetStatesAsync(CAMS_WCF.Contracts.AssetId[] ads);

  [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAMSDataInterface/GetEvents", ReplyAction = "http://tempuri.org/ICAMSDataInterface/GetEventsResponse")]
  CAMS_WCF.Contracts.PkgQueryResultParams GetEvents(CAMS_WCF.Contracts.AssetId[] ads, string[] atypes, string[] etypes, System.DateTime startTimeGMT, System.DateTime endTimeGMT);

  [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAMSDataInterface/GetEvents", ReplyAction = "http://tempuri.org/ICAMSDataInterface/GetEventsResponse")]
  System.Threading.Tasks.Task<CAMS_WCF.Contracts.PkgQueryResultParams> GetEventsAsync(CAMS_WCF.Contracts.AssetId[] ads, string[] atypes, string[] etypes, System.DateTime startTimeGMT, System.DateTime endTimeGMT);

  [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAMSDataInterface/GetRealtimePoints", ReplyAction = "http://tempuri.org/ICAMSDataInterface/GetRealtimePointsResponse")]
  CAMS_WCF.Contracts.PkgRealtimePointResults GetRealtimePoints(CAMS_WCF.Contracts.AssetId aid, System.DateTime start, System.DateTime end);

  [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAMSDataInterface/GetRealtimePoints", ReplyAction = "http://tempuri.org/ICAMSDataInterface/GetRealtimePointsResponse")]
  System.Threading.Tasks.Task<CAMS_WCF.Contracts.PkgRealtimePointResults> GetRealtimePointsAsync(CAMS_WCF.Contracts.AssetId aid, System.DateTime start, System.DateTime end);

  [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAMSDataInterface/GetPlotData", ReplyAction = "http://tempuri.org/ICAMSDataInterface/GetPlotDataResponse")]
  CAMS_WCF.Contracts.PkgPlotPointResults GetPlotData(CAMS_WCF.Contracts.PlotPointRequest[] req);

  [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAMSDataInterface/GetPlotData", ReplyAction = "http://tempuri.org/ICAMSDataInterface/GetPlotDataResponse")]
  System.Threading.Tasks.Task<CAMS_WCF.Contracts.PkgPlotPointResults> GetPlotDataAsync(CAMS_WCF.Contracts.PlotPointRequest[] req);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICAMSDataInterfaceChannel : ICAMSDataInterface, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CAMSDataInterfaceClient : System.ServiceModel.ClientBase<ICAMSDataInterface>, ICAMSDataInterface
{

  public CAMSDataInterfaceClient()
  {
  }

  public CAMSDataInterfaceClient(string endpointConfigurationName) :
          base(endpointConfigurationName)
  {
  }

  public CAMSDataInterfaceClient(string endpointConfigurationName, string remoteAddress) :
          base(endpointConfigurationName, remoteAddress)
  {
  }

  public CAMSDataInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
          base(endpointConfigurationName, remoteAddress)
  {
  }

  public CAMSDataInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
          base(binding, remoteAddress)
  {
  }

  public CAMS_WCF.Contracts.PkgLastPositionResults GetLastPositionInfoAll()
  {
    return base.Channel.GetLastPositionInfoAll();
  }

  public System.Threading.Tasks.Task<CAMS_WCF.Contracts.PkgLastPositionResults> GetLastPositionInfoAllAsync()
  {
    return base.Channel.GetLastPositionInfoAllAsync();
  }

  public CAMS_WCF.Contracts.PkgLastPositionResults GetLastPositionInfo(CAMS_WCF.Contracts.AssetId[] ads)
  {
    return base.Channel.GetLastPositionInfo(ads);
  }

  public System.Threading.Tasks.Task<CAMS_WCF.Contracts.PkgLastPositionResults> GetLastPositionInfoAsync(CAMS_WCF.Contracts.AssetId[] ads)
  {
    return base.Channel.GetLastPositionInfoAsync(ads);
  }

  public CAMS_WCF.Contracts.PkgMaintenanceResults GetMaintenanceInfo(CAMS_WCF.Contracts.MaintenanceRequest[] mr)
  {
    return base.Channel.GetMaintenanceInfo(mr);
  }

  public System.Threading.Tasks.Task<CAMS_WCF.Contracts.PkgMaintenanceResults> GetMaintenanceInfoAsync(CAMS_WCF.Contracts.MaintenanceRequest[] mr)
  {
    return base.Channel.GetMaintenanceInfoAsync(mr);
  }

  public CAMS_WCF.Contracts.PkgAssetFilterResults GetMaintenanceAssets()
  {
    return base.Channel.GetMaintenanceAssets();
  }

  public System.Threading.Tasks.Task<CAMS_WCF.Contracts.PkgAssetFilterResults> GetMaintenanceAssetsAsync()
  {
    return base.Channel.GetMaintenanceAssetsAsync();
  }

  public CAMS_WCF.Contracts.PkgAssetFilterResults GetAssetFilters()
  {
    return base.Channel.GetAssetFilters();
  }

  public System.Threading.Tasks.Task<CAMS_WCF.Contracts.PkgAssetFilterResults> GetAssetFiltersAsync()
  {
    return base.Channel.GetAssetFiltersAsync();
  }

  public CAMS_WCF.Contracts.PkgEventFilterResults GetEventFilters()
  {
    return base.Channel.GetEventFilters();
  }

  public System.Threading.Tasks.Task<CAMS_WCF.Contracts.PkgEventFilterResults> GetEventFiltersAsync()
  {
    return base.Channel.GetEventFiltersAsync();
  }

  public CAMS_WCF.Contracts.PkgEventFilterBaseResults GetEventFiltersFromAsset(CAMS_WCF.Contracts.AssetId aid)
  {
    return base.Channel.GetEventFiltersFromAsset(aid);
  }

  public System.Threading.Tasks.Task<CAMS_WCF.Contracts.PkgEventFilterBaseResults> GetEventFiltersFromAssetAsync(CAMS_WCF.Contracts.AssetId aid)
  {
    return base.Channel.GetEventFiltersFromAssetAsync(aid);
  }

  public CAMS_WCF.Contracts.PkgAssetStatesParams GetAssetStates(CAMS_WCF.Contracts.AssetId[] ads)
  {
    return base.Channel.GetAssetStates(ads);
  }

  public System.Threading.Tasks.Task<CAMS_WCF.Contracts.PkgAssetStatesParams> GetAssetStatesAsync(CAMS_WCF.Contracts.AssetId[] ads)
  {
    return base.Channel.GetAssetStatesAsync(ads);
  }

  public CAMS_WCF.Contracts.PkgQueryResultParams GetEvents(CAMS_WCF.Contracts.AssetId[] ads, string[] atypes, string[] etypes, System.DateTime startTimeGMT, System.DateTime endTimeGMT)
  {
    return base.Channel.GetEvents(ads, atypes, etypes, startTimeGMT, endTimeGMT);
  }

  public System.Threading.Tasks.Task<CAMS_WCF.Contracts.PkgQueryResultParams> GetEventsAsync(CAMS_WCF.Contracts.AssetId[] ads, string[] atypes, string[] etypes, System.DateTime startTimeGMT, System.DateTime endTimeGMT)
  {
    return base.Channel.GetEventsAsync(ads, atypes, etypes, startTimeGMT, endTimeGMT);
  }

  public CAMS_WCF.Contracts.PkgRealtimePointResults GetRealtimePoints(CAMS_WCF.Contracts.AssetId aid, System.DateTime start, System.DateTime end)
  {
    return base.Channel.GetRealtimePoints(aid, start, end);
  }

  public System.Threading.Tasks.Task<CAMS_WCF.Contracts.PkgRealtimePointResults> GetRealtimePointsAsync(CAMS_WCF.Contracts.AssetId aid, System.DateTime start, System.DateTime end)
  {
    return base.Channel.GetRealtimePointsAsync(aid, start, end);
  }

  public CAMS_WCF.Contracts.PkgPlotPointResults GetPlotData(CAMS_WCF.Contracts.PlotPointRequest[] req)
  {
    return base.Channel.GetPlotData(req);
  }

  public System.Threading.Tasks.Task<CAMS_WCF.Contracts.PkgPlotPointResults> GetPlotDataAsync(CAMS_WCF.Contracts.PlotPointRequest[] req)
  {
    return base.Channel.GetPlotDataAsync(req);
  }
}
